apiVersion: v1
kind: Pod
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: streamlit
    image: quay.io/daniel_casali/pymilvus-jupyter-streamlit:v2.3.1
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    ports:
    - containerPort: 8501
      name: streamlit
