apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cpu-notebook
  name: cpu-notebook
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: http
  to:
    kind: Service
    name: cpu-notebook
